name: Build and Release Book

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LaTeX dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          texlive-latex-base \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          texlive-bibtex-extra \
          biber \
          latexmk \
          pandoc \
          calibre \
          ghostscript \
          texlive-science \
          texlive-pictures

    - name: Build PDF
      working-directory: wayland-book
      run: |
        make pdf

    - name: Build EPUB
      working-directory: wayland-book
      continue-on-error: true
      run: |
        make epub || echo "EPUB build failed, continuing..."

    - name: Build Kindle PDF
      working-directory: wayland-book
      run: |
        make pdf-kindle

    - name: Rename files for release
      working-directory: wayland-book
      run: |
        cp main.pdf wayland-book.pdf

    - name: Get book statistics
      working-directory: wayland-book
      run: |
        make stats > build-stats.txt
        cat build-stats.txt

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: wayland-book-pdf
        path: wayland-book/wayland-book.pdf
        retention-days: 30

    - name: Upload Kindle PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: wayland-book-kindle-pdf
        path: wayland-book/wayland-book-kindle.pdf
        retention-days: 30

    - name: Upload EPUB artifact
      uses: actions/upload-artifact@v4
      if: hashFiles('wayland-book/wayland-book.epub') != ''
      with:
        name: wayland-book-epub
        path: wayland-book/wayland-book.epub
        retention-days: 30

    - name: Upload build statistics
      uses: actions/upload-artifact@v4
      with:
        name: build-statistics
        path: wayland-book/build-stats.txt
        retention-days: 30

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          wayland-book-pdf/wayland-book.pdf
          wayland-book-kindle-pdf/wayland-book-kindle.pdf
          wayland-book-epub/wayland-book.epub
          build-statistics/build-stats.txt
        body: |
          ## Wayland Book Release

          This release includes the book in multiple formats:

          - **wayland-book.pdf** - Full PDF version with bibliography and index
          - **wayland-book-kindle.pdf** - Optimized PDF for e-readers (smaller file size)
          - **wayland-book.epub** - EPUB format for e-book readers (experimental)
          - **build-stats.txt** - Book statistics (pages, chapters, etc.)

          ### Installation

          Simply download the format you prefer and open with your PDF reader or e-book application.

          ### Building from Source

          ```bash
          git clone https://github.com/1ay1/wayland_book.git
          cd wayland_book/wayland-book
          make pdf
          ```

          See [README.md](https://github.com/1ay1/wayland_book/blob/main/README.md) for detailed build instructions.

          ### Contributing

          Contributions are welcome! Please see the repository for guidelines.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
